### ISSUE TITLE
Access nodes list for tenant owner

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-ns-filter#21]
# Describe the feature
As evolution for this project, we need to add an ability to also list nodes by tenant labels.
When user asks for a tenant, he is able to provision nodes for his tenant in different clouds using different pre-defined node flavours (BYOD - Bring Your Own Device). We will add specific labels to nodes, showing in which cloud this node is, what interfaces it has (backend, frontend) and other specific labels. I would be useful, the tenant owner is able to list his own nodes only.

# What would the new user story look like?
1. the Cluster Admin creates the Tenant adding the nodeSelector field and the .metadata.annotations pair `capsule.clastix.io/enable-node-listing: "true"`
2. the Tenant Owner with support of the Cluster Admin (getting joining token from control plane requires admin permissions) adds the nodes marked with the label `capsule.clastix.io/tenant=${tenant_name}` labels provided
3. if the Tenant Owner is NOT entitled to list their nodes, we don't intercept and let Kubernetes handle it with the RBAC error.
4. with the `capsule-ns-filter` we're going to add add a new endpoint for nodes, i.e. `/api/v1/nodes` retrieving the available Tenant resources for the user and building the labelSelector as we're doing with Namespaces.

# Expected behavior
As tenant owner of a tenant with `capsule.clastix.io/enable-node-listing: "true"`, I should be able to list my own nodes only, e.g. `kubectl get nodes`.

Make sure the cluster admin only sets the `capsule.clastix.io/enable-node-listing: "true"` and does not give RBAC permissions to list nodes at cluster. If for some reason, the tenant owner is able to bypass the filter and directly asks the `kube-apiserver`, he gets the entire list of cluster nodes.

**Comment by gdurifw** [comment]
Hi Bsctl. In our enviroment we give specific nodes to a Tenant thanks to Capsule.
Would be very nice to have this feature in order to enable our Tenant to list their nodes.

There are news about? We can provide some help?
G.

**Comment by prometherion** [comment]
Help here would be required, since I got an hypothetical implementation but a bit worried.

What happens if Capsule would add some labels to Nodes?

Asking these because right now we're taking advantage of Kubernetes API Server filtering capabilities, meaning we can use the `in` logical operator that is the core of our implementation.

What I'm not really happy about this is changing resources at runtime, making the infrastructure non immutable by design.

**Comment by MaxFedotov** [comment]
Hi @gdurifw, i've started implementing this feature, but as we are preparing for new year events, will be able to continue with it only in January. So if you would like to implement it - i will be very grateful :)

**Comment by bsctl** [comment]
> What I'm not really happy about this is changing resources at runtime, making the infrastructure non immutable by design.

@prometherion not sure what you mean here. This feature is only applicable to the scenario where a nodes pool is assigned to a tenant (Boyd). No need to change the infrastructure here. A node pool is assigned to a tenant when the tenant is on boarded. Nodes are labeled after they joint the control plane an that label is never to be changed. Please articulate your POV with more details.
